[package]
name = "manga-news"
version = "0.1.0"
authors = ["Alfrheim <1399702+Alfrheim@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
scraper = "0.10.0"
select = "0.4.1"
